### PR TITLE
Fix probe crashing when encountering non audio or video streams

### PR DESCRIPTION
**Pull request by ngrunwald**
Probe fn crashes when encountering a stream that is not ausio or video. This just allows the other types to appear in the streams list without particular treatment.

### CODE REVIEW

**Comment by phronmophobic** [comment]
Thanks for the report. Do you know where I can get media of these types to test things out?

Also, for clarity, there's usually not much of a distinction between "crashing" and "throwing an exception". However, since clj-media calls out to native code, the distinction is important since some types of bugs in clj-media can lead to hard crashing the JVM!

**Comment by ngrunwald** [comment]
Yes, my bad, it was of course a run-of-the-mill exception about condp missing a default branch.

About the file; I have a few rather biggish files with a data stream that are posing problems and I am testing with, I can send you one if you want.

Working a bit more with the file, there's actually another bug linked to this when trying to extract the frames from the files, around https://github.com/phronmophobic/clj-media/blob/a22d1248d937ea6f096b51cc7674bb897a25300a/src/com/phronemophobic/clj_media/impl/filter/media.clj#L82

-media is trying to find a decoder for every stream in the file, and it obviously throws for the data stream. I think just skipping the streams that are neither audio nor video should be fine, I will add that to the PR if that's fine?

**Comment by phronmophobic** [comment]
> I think just skipping the streams that are neither audio nor video should be fine, I will add that to the PR if that's fine?

I don't think silently throwing away data is the right thing to do. If supporting streams that aren't audio or video isn't a priority, I would rather have something that explicitly filters for audio/video streams rather than silently ignoring them.

I'm working on some other changes that might make it easier to support (or more easily ignore) streams that aren't audio or video. If you have some example media with non audio/video streams, that would help!

**Comment by ngrunwald** [comment]
> I don't think silently throwing away data is the right thing to do. If supporting streams that aren't audio or video isn't a priority, I would rather have something that explicitly filters for audio/video streams rather than silently ignoring them.

I agree fully, it's just that right now I think all the -media fn does is process frames; and that's not how these streams work from what I understand (but I may be wrong, I don't have much experience on the subject). And given how the code is written, -media is called on all streams even if you specifically traget another stream, so that makes the whole file unusable.

But even without having a lot a specific code, I think the very least should be to be able to copy these streams as is to the output. 

Here is an example of video with a data stream. I'm not sure of the copyright status of this right now, so I'd be grateful if you do not commit it publicly. I can probably et someone at work next week to produce a public domain video from the same workflow for this purpose. Thanks!
https://fromsmash.com/video-file-with-data-stream

**Comment by phronmophobic** [comment]
Thanks for sharing an example. I won't use it for anything except testing locally (which is helpful to have).

There's very little documentation on data streams. It seems like it's some opaque data that some format containers support, but I'm having trouble figuring out how to treat AVMEDIA_TYPE_DATA packets.

Anyway, I have some WIP changes that should help strip out AVMEDIA_TYPE_DATA packets or pass them through unchanged.

**Comment by phronmophobic** [comment]
Probing media with non audio/video data should be fixed in 2.1.

You can also explicitly filter for audio/video streams.
```clojure
(clj-media/write!
 (->> (clj-media/file "CORSICA_SHOT_271.mov")
      (clj-media/filter-media-types #{:media-type/video
                                      :media-type/audio}))
 "copy.mp4")
```

**Comment by phronmophobic** [comment]
Let me know if this works for you.

**Comment by ngrunwald** [comment]
Hi, sorry for the delay! The fix is flexible and elegant and works fine in simple cases. I would still argue that there are some problems remaining. For example in my tests, this file with the data stream could not be directly used with avfilters because they used the `-media` fn from `IMediaSource` protocol, which still failed while trying to find an appropriate decoder for the data stream.

I can work around the problem by producing a clean new file and then further processing that in my case, but for the use cases where the user would want to modify some aspect of the file without removing the data streams that could be blocking. Have you got any idea about how to approach this or maybe I am just missing something?

**Comment by phronmophobic** [comment]
@ngrunwald 

>  For example in my tests, this file with the data stream could not be directly used with avfilters because they used the -media fn from IMediaSource protocol, which still failed while trying to find an appropriate decoder for the data stream.
> I can work around the problem by producing a clean new file and then further processing that in my case

You can use the file directly by wrapping it with `clj-media/filter-media` first as shown below. There's no need to create an intermediate file. Note that no processing is done until `clj-media/write!` is called.

```clojure
(def media
  (->> (clj-media/file "CORSICA_SHOT_271.mov")
       (clj-media/filter-media-types #{:media-type/video
                                       :media-type/audio})))

(clj-media/write!
 (->> media
      (avfilter/trim+ {:duration 1e6})
      (avfilter/edgedetect))
 "copy.mp4")
```

> but for the use cases where the user would want to modify some aspect of the file without removing the data streams that could be blocking. Have you got any idea about how to approach this or maybe I am just missing something?

The latest changes actually help support that use case, but there's still some work to do. The challenge is that I can't find really any information about what `:media-type/data` is used for and which container formats support it. If you have an actual use case that requires `:media-type/data`, feel free to file an issue!

**Pull request closed without merging**
